const User = require ('./user')
const DailyPrograms = require ('./dailyPrograms')
const Recipe = require ('./recipe')
const Meal = require ('./meal')
const Ingredients = require ('./ingredients')



const yumurta = new Ingredients('Yumurta', 100, 10, 5, 3)
const sut = new Ingredients('Süt', 125, 2, 12, 20)
const sabah = new Meal('Sabah')
const sutluYumurta = new Recipe('Sütlü Yumurta')
const diyet1 = new DailyPrograms('1.Hafta')

sutluYumurta.addIngredients(sut)
sutluYumurta.addIngredients(yumurta)
sabah.addIngredients(yumurta)
sabah.addIngredients(sut)
// sabah.addRecipe(sutluYumurta)
diyet1.addMeal(sabah)

const yunus = new User('Yunus', 30, 'yunus@yunus.com')
const naciye = new User('Naciye', 25, 'naciye@naciye.com')
const armagan = new User('Armağan', 30, 'armagan@armagan.com')

armagan.followUser(yunus)
naciye.followUser(yunus)
yunus.followUser(naciye)
yunus.followUser(armagan)
yunus.createDailyProgram(diyet1)
naciye.createDailyProgram(diyet1)

// console.log(sabah)
// console.log(sutluYumurta)
// console.log(yumurta)
// yunus.postRecipie(sutluYumurta)
// console.log(sabah)
// console.log(yunus)
yunus.listFollower()
armagan.listFollower()
// listFollowers(yunus)
